### ISSUE TITLE
#11add single line upload function on assign page 

### ISSUE THREAD

**Issue by yylocky** [yylocky/CITS5206-Group3#11]
role-based access control required

**Comment by kylelhk** [comment]
1. Existing records in the database should NOT be replaced by new assignments.  (Changes to the existing records should instead be made in the Edit page.)
2. If any duplicate workload(s) is being assigned, a message should be popped up to remind users of the fact that a workload(s) with the same details has been previously assigned.
3. For the purpose of MVP, we may assume that all users being assigned exist in the user table.  Otherwise, a message should be popped up to remind users about the absence of assignee.
